# test HTTP requests
### use with: HTTP client extension

@apiurl = http://localhost:3000/api
### Get all items
GET {{apiurl}}/items


### Add new item
POST {{apiurl}}/items
Content-Type: application/json

{
  "name": "Appelsiini"
}

### Get item by ID
GET {{apiurl}}/items/1

### delete route for item
DELETE {{apiurl}}/items/1

### Put route for item
PUT {{apiurl}}/items/1
Content-Type: application/json

{
  "name": "Porkkana"
}

// user endpoints

### Get all users
GET {{apiurl}}/users

### Register new user
POST {{apiurl}}/users
Content-Type: application/json


{
  "username": "donald",
  "password": "duck",
  "email": "donald@example.com"
},


### Register new user FAIL when email missing
POST {{apiurl}}/users
Content-Type: application/json


{
  "username": "donald",
  "password": "duck"
},

### User login
POST {{apiurl}}/users/login
Content-Type: application/json


{
  "username": "donald",
  "password": "duck"
},