# test HTTP requests
### use with: HTTP client extension

### Get all items
GET http://localhost:3000/items


### Add new item
POST http://localhost:3000/items
Content-Type: application/json

{
  "name": "Appelsiini"
}

### Get item by ID
GET http://localhost:3000/items/1

### delete route for item
DELETE http://localhost:3000/items/1


### Put route for item
PUT http://localhost:3000/items/1
Content-Type: application/json

{
  "name": "Porkkana"
}